version: "3.8"

services:

  app-mysql:
    image: mysql:5.7.40
    container_name: app-mysql
    networks:
      - avosh-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=AvDb
      - MYSQL_USER=db-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  redis-server:
    container_name: redis
    image: redis
    networks:
      - avosh-network
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php-myadmin
    networks:
      - avosh-network
    ports:
      - "8082:80"
    restart: always

    links:
      - app-mysql
    environment:
      PMA_HOST: app-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  app-main:
    image: c84fefaad081
    restart: on-failure
    networks:
      - avosh-network
    links:
      - app-mysql
      - redis-server
    depends_on:
      - app-mysql
      - redis-server
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://app-mysql:3306/AvDb?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Tehran&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: db-user
      SPRING_DATASOURCE_PASSWORD: password
networks:
  avosh-network:
    name: avosh-network