version: "3.8"

services:

  app-mysql:
    image: mysql:5.7.40
    networks:
      - avosh-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  redis-server:
    container_name: redis
    image: redis
    networks:
      - avosh-network
    ports:
      - 6379:6379

  app-main:
    image: b2b30e66606f
    restart: on-failure
    networks:
      - avosh-network
    depends_on:
      - redis-server
      - app-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3306
networks:
    avosh-network:
      name: avosh-network